apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-redis-app
  template:
    metadata:
      labels:
        app: node-redis-app
    spec:
      containers:
      - name: node-redis-app
        image: proyectolibreria.azurecr.io/library-custom-api:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: node-redis-app-service
spec:
  selector:
    app: node-redis-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
